# Generated by Django 6.0.1 on 2026-01-21 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='')),
                ('description', models.CharField(default='')),
                ('coverImage', models.CharField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='recipeinrgedient',
            name='name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='stepContent',
            field=models.CharField(default=''),
        ),
        migrations.CreateModel(
            name='RecipeBookLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('recipeBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipebook')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='')),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
